--ozone-platform-hint=auto
--enable-gpu-rasterization
--enable-zero-copy
--enable-features=VaapiVideoDecodeLinuxGL,CanvasOopRasterization
--disable-features=UseChromeOSDirectVideoDecoder
--password-store=kwallet6
